import type { RedactedExtraction, TransactionEvent } from "./transactions";

export interface DamageSignal { type: string; confidence: number; matched_box: boolean }
export interface VideoEvidencePayload { counts: Record<string, number>; unit_count: number; damage_signals: DamageSignal[]; confidence: number }
export interface EvidenceRecordPublicView { id:string; transaction_id:string; milestone_id:string|null; evidence_type:string; source:string; submitted_by_user_id:string; submitted_by_entity_id:string; external_reference:string|null; file_sha256:string|null; payload:Record<string,unknown>; verification_status:string; analyzer_provider:string|null; analyzer_version:string|null; created_at:string; verified_at:string|null }
export interface EvidenceRecordSummary { id:string; evidence_type:string|null; source:string|null; verification_status:string|null; submitted_by_entity_id:string|null; submitted_by_role:string|null; external_reference:string|null; file_sha256:string|null; analyzer_provider:string|null; analyzer_version:string|null; created_at:string|null; verified_at:string|null; milestone_id:string|null }
export interface EIrsaliyeSubmitRequest { external_reference:string; delivered_quantity:number; milestone_id?:string|null }
export interface EvidenceBundle { transaction:{id:string;state:string;created_at:string}|null; extraction:RedactedExtraction|null; validator_report:unknown; tracking_policy:unknown; approvals:{party:string;created_at:string}[]; events:TransactionEvent[]; evidence_records:EvidenceRecordSummary[]; ratification_package:{id:string;version:number;status:string;package_hash:string;ratifications:Record<string,{ratified:boolean;approved_at:string|null}>}|null; decision:{action?:string;capture_ratio?:number;manual_review_required?:boolean}|null; snapshot_hash:string; generated_at:string }
export interface EvidenceSnapshotResponse { snapshot_id:string; snapshot_hash:string; created:boolean; bundle:EvidenceBundle }
export interface FundingUnitProjection { id:string; transaction_id:string; milestone_id:string; sequence:number; title:string; amount_minor:number; currency:string; eligibility_type:string; status:string; release_instruction_id:string|null; release_instruction_status:string|null }
export interface MilestoneProjection { id:string; transaction_id:string; rule_index:number; title:string; trigger_type:string; percentage_basis_points:number; amount_minor:number; currency:string; required_evidence:string[]; release_mode:string; status:string; released_amount_minor:number; created_at:string; updated_at:string; funding_units:FundingUnitProjection[] }
export interface MilestoneFundingProjection { transaction_id:string; package_id:string|null; milestones:MilestoneProjection[] }
